### ISSUE TITLE
Insecure errors in log

### ISSUE THREAD

**Issue by zedr32** [gijsvdhoven/homeassistant-addons#6]
I’m struggling to find a workaround for this issue. When using your addon, I see the following log entries and a prompt on my 2024 55" Frame Samsung TV using FW 1201

SamsungTvRemote: "You must grant permission for your device to connect."

When I select "Yes," the prompt reappears again.

The following log entries are appended each time, and the issue repeats whenever I restart the addon.

Does anyone have suggestions for resolving this? I’d really like to push media to the Frame from Home Assistant if possible.

Using 192.168.1.33 as the IP of the Samsung Frame
/usr/lib/python3.11/site-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.33'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
Traceback (most recent call last):
  File "//art.py", line 160, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "//art.py", line 76, in main
    await tv.start_listening()
  File "/usr/lib/python3.11/site-packages/samsungtvws/async_art.py", line 108, in start_listening
    await self.open()
  File "/usr/lib/python3.11/site-packages/samsungtvws/async_art.py", line 85, in open
    await super().open()
  File "/usr/lib/python3.11/site-packages/samsungtvws/async_connection.py", line 75, in open
    raise exceptions.ConnectionFailure(response)
samsungtvws.exceptions.ConnectionFailure: {'event': 'ms.channel.timeOut'}

**Comment by jswent** [comment]
Hey @zedr32 @davidfrem I've got 2024 models and was encountering the same problem, it's an issue with the way token retrieval is done by the `async_art` module of NickWaterton's `samsungtvws` library - so the problem isn't related to this repo.

If you're interested in just controlling the frame functionality, you can check out my [frame_art](https://github.com/jswent/frame_art) integration. I haven't added image uploading (as I don't do that via HA), but you can select the artwork by content id.

**Comment by Kuglikrug** [comment]
Hi, i just wanted to add that i have the same problem with my 2024 55" Frame Samsung TV.
@jswent your [frame_art](https://github.com/jswent/frame_art) integration does work for turning on/off art mode but i cant control/change the art that is displayed

**Comment by gijsvdhoven** [comment]
sorry I don't own a newer model so I can 't test.
